include: package:lints/recommended.yaml

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: false
    implicit-casts: false
linter:
  rules:
    - always_declare_return_types
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cast_nullable_to_non_nullable
    - directives_ordering
    - literal_only_boolean_expressions
    - null_check_on_nullable_type_parameter
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - prefer_const_constructors
    - prefer_interpolation_to_compose_strings
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_late_for_private_fields_and_variables
