import 'package:flutter/foundation.dart';
import 'package:reactive_forms/validators/validators.dart';
import 'package:rxdart/rxdart.dart';

/// Tracks the value and validation status of an individual form control.
class FormControl<T> extends ChangeNotifier implements ValueListenable<T> {
  final PublishSubject _onStatusChangedSubject = PublishSubject();
  final PublishSubject _onFocusChangedSubject = PublishSubject();
  bool _focused = false;
  T _value;
  T _defaultValue;

  /// The list of functions that determines the validity of this control.
  final List<ValidatorFunction> validators;

  /// An object containing any errors generated by failing validation,
  /// or empty [Map] if there are no errors.
  final Map<String, dynamic> errors = {};

  /// Represents if the control is touched or not. A control is touched when
  /// the user taps on the ReactiveFormField widget and then remove focus or
  /// completes the text edition. Validation messages will begin to show up
  /// when the FormControl is touched.
  bool touched;

  /// Creates a new FormControl instance, optionally pass [defaultValue]
  /// and [validators]. You can set [touched] to true to force the validation
  /// messages to show up at the very first time the widget builds.
  ///
  /// You can also force the data type of this control by specifying it
  ///
  /// ### Example:
  /// ```dart
  /// final priceControl = FormControl<double>(defaultValue: 0.0);
  /// ```
  ///
  FormControl({
    T defaultValue,
    this.validators = const [],
    this.touched = false,
  }) : _value = defaultValue {
    _validate();
  }

  /// Returns the current value of the control.
  @override
  T get value => _value;

  /// Returns the default value of the control.
  T get defaultValue => _defaultValue;

  /// True if the control is marked as focused.
  bool get focused => _focused;

  /// Sets the [newValue] as value for the form control.
  set value(T newValue) {
    if (_value == newValue) return;
    _value = newValue;
    _validate();
    notifyListeners();
  }

  @override
  void dispose() {
    //this._onStatusChangedSubject.close();
    this._onFocusChangedSubject.close();
    super.dispose();
  }

  /// A [Stream] that emits an event every time the validation status of
  /// the control changes.
  Stream get onStatusChanged => _onStatusChangedSubject.stream;

  /// A [Stream] that emits an event every time the focus status of
  /// the control changes.
  Stream get onFocusChanged => _onFocusChangedSubject.stream;

  /// True if the control doesn't has validations errors.
  bool get valid => this.errors.keys.length == 0;

  /// True if the control has validations errors.
  bool get invalid => !this.valid;

  /// Sets errors on a form control when running validations manually,
  /// rather than automatically.
  ///
  /// ### Example:
  ///
  /// ```dart
  /// final passwordConfirmation = FormControl();
  ///
  /// passwordConfirmation.addError({'mustMatch': true});
  ///```
  ///
  /// See also [FormControl.errors]
  ///
  void addError(Map<String, dynamic> error) {
    final prevStatus = this.valid;
    this.errors.addAll(error);
    if (prevStatus != this.valid) {
      _onStatusChangedSubject.add(this.valid);
    }
  }

  /// Remove errors by name.
  ///
  /// ### Example:
  ///
  ///```dart
  /// final passwordConfirmation = FormControl();
  ///
  /// passwordConfirmation.removeError('mustMatch');
  ///```
  ///
  /// See also [FormControl.errors]
  ///
  void removeError(String errorName) {
    final prevStatus = this.valid;
    this.errors.remove(errorName);
    if (prevStatus != this.valid) {
      _onStatusChangedSubject.add(this.valid);
    }
  }

  /// Resets the form control, marking it as untouched,
  /// and setting the [value] to [defaultValue].
  void reset() {
    this.touched = false;
    this.value = this.defaultValue;
  }

  /// Remove focus on a ReactiveFormField widget without the interaction
  /// of the user.
  ///
  /// ### Example:
  ///
  /// ```dart
  /// final formControl = form.formControl('name');
  ///
  /// // UI text field lose focus
  /// formControl.unfocus();
  ///```
  ///
  void unfocus() {
    if (this._focused) {
      this._focused = false;
      this._onFocusChangedSubject.add(this._focused);
    }
  }

  /// Sets focus on a ReactiveFormField widget without the interaction
  /// of the user.
  ///
  /// ### Example:
  ///
  /// ```dart
  /// final formControl = form.formControl('name');
  ///
  /// // UI text field get focus and the device keyboard pop up
  /// formControl.focus();
  ///```
  ///
  void focus() {
    if (!this._focused) {
      this._focused = true;
      this._onFocusChangedSubject.add(this._focused);
    }
  }

  void _validate() {
    this.errors.clear();
    this.validators.forEach((validator) {
      final error = validator(this._value);
      if (error != null) {
        this.errors.addAll(error);
      }
    });
  }
}
